apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-emptydir-pod
spec:
  containers:
  - name: kubernetes-emptydir-pod
    image: arisu1000/simple-container-app:latest
    volumeMounts:
      - mountPath: /emptydir
        name: emptydir-vol
  volumes:
  - name: emptydir-vol
    emptyDir: {}
